In [44]:
import torch 

In [45]:
xs = [
  [2.0, 3.0, -1.0], # input 1 => the desired target is 1.0 
  [3.0, -1.0, 0.5], # input 2 => the desired target is -1.0 
  [0.5, 1.0, 1.0],  # input 3 => the desired target is -1.0 
  [1.0, 1.0, -1.0], # input 4 => the desired taregt is 1.0 
]
ys = [1.0, -1.0, -1.0, 1.0]

In [46]:
# first we need to convert these python lists to tensors 
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [47]:
# compute wx + b (for simplicity, we are going to leave out the bias term b )
# Normally its x @ w 

# initialize random weights from a normal distribution 
# xs is a (4, 3) matrix 
# W should be a (3, 1) for a one layer NN 
# output matrix is (4, 3) @ (3, 1) => (4, 1) 
# (4, 1) gives us the 4 predicted values from the NN 
g = torch.Generator().manual_seed(2147483547)
W = torch.randn((3, 1), generator=g, requires_grad=True)

In [48]:
W

tensor([[ 0.7187],
        [-0.5081],
        [-1.3872]], requires_grad=True)

In [121]:
# compute x @ w 
ypred = xs @ W 
ypred 

tensor([[ 1.1483],
        [-0.9396],
        [-1.0316],
        [ 1.0642]], grad_fn=<MmBackward0>)

In [122]:
loss = sum([(ypred - ys)**2 for ys, ypred in zip(ys, ypred)])
loss

tensor([0.0308], grad_fn=<AddBackward0>)

In [123]:
loss.backward()

In [124]:
W.grad

tensor([[ 1.0526],
        [ 0.8341],
        [-0.4277]])

In [125]:
W.data -= 0.05 * W.grad

In [120]:
W.grad.zero_()

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
for _ in range(20):
    ypred = xs @ W 
    loss = sum([(ypred - ys)**2 for ys, ypred in zip(ys, ypred)])
    loss.backward()
    W.data -= 0.05 * W.grad
    W.grad.zero_()

In [126]:
for _ in range(20):
    ypred = xs @ W
    loss = ((ypred.squeeze() - ys) ** 2).sum()
    
    loss.backward()
    
    with torch.no_grad():
        W.data -= 0.05 * W.grad
    
    W.grad.zero_()
    
    print(loss.item())

0.021511442959308624
0.03593873977661133
0.025274675339460373
0.01784414052963257
0.012665942311286926
0.009056869894266129
0.006541142240166664
0.00478733005002141
0.0035645575262606144
0.00271195312961936
0.0021173926070332527
0.001702755456790328
0.0014135712990537286
0.001211871625855565
0.0010711753275245428
0.0009730316232889891
0.0009045653278008103
0.0008568036719225347
0.0008234785636886954
0.0008002256508916616
