In [79]:
import torch

In [80]:
xs = [
  [2.0, 3.0, -1.0],
  [3.0, -1.0, 0.5],
  [0.5, 1.0, 1.0],
  [1.0, 1.0, -1.0],
]
ys = [1.0, -1.0, -1.0, 1.0]

In [81]:
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [82]:
xs.shape

torch.Size([4, 3])

In [83]:
ys.shape

torch.Size([4])

In [84]:
# We want to create a very simple NN with just 1 layer 

# because xs is a (4,3) matrix 
# out layer will have 1 neuron with 3 weights => (3,1)

# normally, its xw which will be 
# (4,3) @ (3,1) => (4, 1)

# Initialize w matrix 
g = torch.Generator().manual_seed(2147483547)
W = torch.rand((3, 1), generator=g, requires_grad=True)


In [189]:
# now lets compute wx (as xw)
ypred = xs @ W

In [190]:
ypred

tensor([[ 0.9675],
        [-0.8551],
        [ 0.3132],
        [ 0.2911]], grad_fn=<MmBackward0>)

In [191]:
loss = sum([(ypred - ys)**2 for ys, ypred in zip(ys, ypred)])
loss

tensor([2.2492], grad_fn=<AddBackward0>)

In [192]:
loss.backward()

In [193]:
print(W.grad)

tensor([[0.6352],
        [0.7240],
        [4.2541]])


In [188]:
W.data -= 0.01 * W.grad
W.grad.zero_()

tensor([[0.],
        [0.],
        [0.]])